### ISSUE TITLE
#:quotes-only-when-needed? doesn't seem to work

### ISSUE THREAD

**Issue by sorawee** [jbclements/csv-writing#4]
```
> (define (tsv-string-converter str)
    (match str
      [(regexp #px"\t")
       (error 'tsv-string-converter "no tabs allowed: ~e" str)]
      [other str]))
> (define default-tsv-printing-params2                                                                                                                                                   
    (make-csv-printing-params                                                                                                                                                             
      #:string-cell->string tsv-string-converter                                                                                                                                        
      #:quotes-only-when-needed? #f                                                                                                                                                        
      #:column-separator "\t"))
> (table-row->string '("1" "2\n3") #:printing-params default-tsv-printing-params2)
"1\t2\n3"
```

**Comment by jbclements** [comment]
This looks like a doc bug to me. In particular, there are a number of different parameters that "overlap"; in this case, if you define your own string-cell->string function, then you've "taken control" of string translation, and the quotes-only-when-needed? setting will be ignored. This is also true of the quoted-double-quote string.

I think it might be sufficient just to point out that these are used by the default string converter, but that they'll be ignored if you supply your own.

**Comment by jbclements** [comment]
Does that make sense to you?

**Comment by sorawee** [comment]
Yep!

**Comment by sorawee** [comment]
A better interface would not allow users to specify both options in the same time. Is that something that can be done? I guess it would make it not backward compatible though...

**Comment by jbclements** [comment]
Actually, that does make good sense, and since the full structure can be defined, you have a workaround if for some reason you want something else. If you call the default method, for instance.

**Comment by jbclements** [comment]
Of course, it wound up being more interesting than that...
